"""empty message

Revision ID: 1f8ff868df54
Revises: 
Create Date: 2020-12-08 19:29:03.797735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8ff868df54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('especializacao', sa.String(length=50), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('numero_de_projetos', sa.Integer(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_pessoa'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('projeto',
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=False),
    sa.Column('coord', sa.String(length=3), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_projeto')
    )
    op.create_table('membro_equipe',
    sa.Column('id_membro', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=10), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=True),
    sa.Column('id_projeto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id_pessoa'], ),
    sa.ForeignKeyConstraint(['id_projeto'], ['projeto.id_projeto'], ),
    sa.PrimaryKeyConstraint('id_membro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membro_equipe')
    op.drop_table('projeto')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
