"""empty message

Revision ID: 6c8377f09fca
Revises: 1f8ff868df54
Create Date: 2020-12-08 19:32:21.468204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8377f09fca'
down_revision = '1f8ff868df54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa', sa.Column('especial', sa.String(length=50), nullable=True))
    op.drop_column('pessoa', 'especializacao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa', sa.Column('especializacao', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('pessoa', 'especial')
    # ### end Alembic commands ###
